package es.jbp.comun.configurador;

import es.jbp.comun.configurador.estructura.Elemento;
import es.jbp.comun.configurador.estructura.NodoElemento;
import java.util.List;
import javax.swing.text.JTextComponent;

/**
 * Panel para la edición de un elemento
 *
 * @author jberjano
 */
public class PanelEditor extends javax.swing.JPanel {

    private NodoElemento nodoElemento;
    private String valorAnterior = "";

    /**
     * Creates new form PanelEditor
     */
    public PanelEditor(NodoElemento nodoElemento) {
        initComponents();

        boolean mostrarEdicion = false;
        boolean mostrarAplicar = false;

        this.nodoElemento = nodoElemento;
        labelTitulo.setText(nodoElemento.getCamino());
        if (nodoElemento.getIcono() != null) {
            labelTitulo.setIcon(nodoElemento.getIcono());
        }

        Elemento elemento = nodoElemento.getElemento();
        if (elemento != null) {
            mostrarAplicar = nodoElemento.esArray();
            textDescripcion.setText(elemento.getDescripcion());

            if (elemento.tieneEdicion()) {
                textValorPorDefecto.setText(elemento.getValorPorDefecto());

                List<String> opciones = elemento.getOpciones();
                if (opciones == null) {
                    opciones = Ventana.getInstancia().getMemorando().getValoresRecordados(elemento.getNombre());
                }

                if (opciones != null) {
                    for (String opcion : opciones) {
                        comboValor.addItem(opcion);
                    }
                }
                valorAnterior = nodoElemento.getValor();
                comboValor.setSelectedItem(valorAnterior);
                mostrarEdicion = true;
            }
        }

        scrollDescripcion.setVisible(elemento != null);
        labelValorPorDefecto.setVisible(mostrarEdicion);
        textValorPorDefecto.setVisible(mostrarEdicion);
        botonAplicar.setVisible(mostrarAplicar);
        panelValor.setVisible(mostrarEdicion);
    }

    public void capturarValor() {

        String valorActual = ((JTextComponent) comboValor.getEditor().getEditorComponent()).getText();

        if (!valorActual.equals(valorAnterior)) {
            System.out.println(nodoElemento.getCamino() + " = " + valorActual);
            nodoElemento.setValor(valorActual);
            valorAnterior = valorActual;
            if (nodoElemento.esArray()) {
                Ventana.getInstancia().actualizarArbol();
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        labelTitulo = new javax.swing.JLabel();
        filler1 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 8), new java.awt.Dimension(0, 8), new java.awt.Dimension(32767, 8));
        panelValor = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        filler6 = new javax.swing.Box.Filler(new java.awt.Dimension(8, 0), new java.awt.Dimension(8, 0), new java.awt.Dimension(8, 32767));
        comboValor = new javax.swing.JComboBox<>();
        filler7 = new javax.swing.Box.Filler(new java.awt.Dimension(8, 0), new java.awt.Dimension(8, 0), new java.awt.Dimension(8, 32767));
        botonAplicar = new javax.swing.JButton();
        filler2 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 8), new java.awt.Dimension(0, 8), new java.awt.Dimension(32767, 8));
        scrollDescripcion = new javax.swing.JScrollPane();
        textDescripcion = new javax.swing.JTextArea();
        filler3 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 8), new java.awt.Dimension(0, 8), new java.awt.Dimension(32767, 8));
        jPanel1 = new javax.swing.JPanel();
        labelValorPorDefecto = new javax.swing.JLabel();
        filler4 = new javax.swing.Box.Filler(new java.awt.Dimension(8, 0), new java.awt.Dimension(8, 0), new java.awt.Dimension(8, 32767));
        textValorPorDefecto = new javax.swing.JTextField();
        filler5 = new javax.swing.Box.Filler(new java.awt.Dimension(8, 0), new java.awt.Dimension(8, 0), new java.awt.Dimension(8, 32767));

        setBorder(javax.swing.BorderFactory.createEmptyBorder(8, 8, 8, 8));
        setLayout(new javax.swing.BoxLayout(this, javax.swing.BoxLayout.PAGE_AXIS));

        labelTitulo.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        labelTitulo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/es/shs/comun/configurador/imagenes/punto.png"))); // NOI18N
        labelTitulo.setText("Titulo");
        labelTitulo.setAlignmentX(0.5F);
        labelTitulo.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        add(labelTitulo);
        add(filler1);

        panelValor.setMaximumSize(new java.awt.Dimension(32803, 20));
        panelValor.setMinimumSize(new java.awt.Dimension(160, 20));
        panelValor.setLayout(new javax.swing.BoxLayout(panelValor, javax.swing.BoxLayout.LINE_AXIS));

        jLabel1.setText("Valor:");
        panelValor.add(jLabel1);
        panelValor.add(filler6);

        comboValor.setEditable(true);
        comboValor.setMaximumSize(new java.awt.Dimension(32767, 27));
        comboValor.setMinimumSize(new java.awt.Dimension(124, 20));
        comboValor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboValorActionPerformed(evt);
            }
        });
        panelValor.add(comboValor);
        panelValor.add(filler7);

        botonAplicar.setText("Aplicar");
        botonAplicar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonAplicarActionPerformed(evt);
            }
        });
        panelValor.add(botonAplicar);

        add(panelValor);
        add(filler2);

        textDescripcion.setEditable(false);
        textDescripcion.setBackground(java.awt.SystemColor.control);
        textDescripcion.setColumns(20);
        textDescripcion.setLineWrap(true);
        textDescripcion.setRows(5);
        scrollDescripcion.setViewportView(textDescripcion);

        add(scrollDescripcion);
        add(filler3);

        jPanel1.setMaximumSize(new java.awt.Dimension(2147483647, 20));
        jPanel1.setMinimumSize(new java.awt.Dimension(100, 20));
        jPanel1.setPreferredSize(new java.awt.Dimension(100, 20));
        jPanel1.setLayout(new javax.swing.BoxLayout(jPanel1, javax.swing.BoxLayout.LINE_AXIS));

        labelValorPorDefecto.setText("Valor por defecto:");
        jPanel1.add(labelValorPorDefecto);
        jPanel1.add(filler4);

        textValorPorDefecto.setEditable(false);
        textValorPorDefecto.setMaximumSize(new java.awt.Dimension(2147483647, 20));
        jPanel1.add(textValorPorDefecto);
        jPanel1.add(filler5);

        add(jPanel1);
    }// </editor-fold>//GEN-END:initComponents

    private void botonAplicarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonAplicarActionPerformed

        capturarValor();

    }//GEN-LAST:event_botonAplicarActionPerformed

    private void comboValorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboValorActionPerformed
        
        
    }//GEN-LAST:event_comboValorActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonAplicar;
    private javax.swing.JComboBox<String> comboValor;
    private javax.swing.Box.Filler filler1;
    private javax.swing.Box.Filler filler2;
    private javax.swing.Box.Filler filler3;
    private javax.swing.Box.Filler filler4;
    private javax.swing.Box.Filler filler5;
    private javax.swing.Box.Filler filler6;
    private javax.swing.Box.Filler filler7;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel labelTitulo;
    private javax.swing.JLabel labelValorPorDefecto;
    private javax.swing.JPanel panelValor;
    private javax.swing.JScrollPane scrollDescripcion;
    private javax.swing.JTextArea textDescripcion;
    private javax.swing.JTextField textValorPorDefecto;
    // End of variables declaration//GEN-END:variables

}
