package es.jbp.comun.configurador;

import es.jbp.comun.configurador.estructura.Estructura;
import es.jbp.comun.configurador.estructura.NodoElemento;
import javax.swing.event.TreeSelectionEvent;
import javax.swing.event.TreeSelectionListener;
import javax.swing.tree.TreePath;

/**
 * Panel principal
 *
 * @author jberjano
 */
public class PanelConfiguracion extends javax.swing.JPanel {

    protected Estructura estructura;
    protected PanelEditor panelEditorActual;
    protected ModeloArbolElementos modeloArbol;
    protected TreeState treeState;
    protected boolean actualizando;
    
    /**
     * Creates new form ArbolConfiguracion
     */
    public PanelConfiguracion() {
        initComponents();
        
        treeState = new TreeState(arbolElementos);
        //arbolElementos.setFont(arbolElementos.getFont().deriveFont(Font.BOLD));
    }

    public void setEstructura(Estructura estructura) {

        this.estructura = estructura;

        modeloArbol = new ModeloArbolElementos(estructura);
        arbolElementos.setModel(modeloArbol);

        arbolElementos.setCellRenderer(new ArbolCellRenderer());

        arbolElementos.addTreeSelectionListener(new TreeSelectionListener() {
            @Override
            public void valueChanged(TreeSelectionEvent e) {
                if (actualizando) {
                    return;
                }
                actualizando = true;                
                
                capturarValor();

                treeState.guardar();
                
                Object seleccionado = arbolElementos.getLastSelectedPathComponent();
                if (seleccionado instanceof NodoElemento) {
                    NodoElemento nodo = (NodoElemento) seleccionado;
                    PanelEditor panel = nodo.getPanelEditor();
                    if (panel == null) {
                        panel = new PanelEditor(nodo);
                        nodo.setPanelEditor(panel);
                    }
                    split.setRightComponent(panel);
                    panelEditorActual = panel;
                }
                actualizarArbol();
                
                treeState.restaurar();
                
                actualizando = false;
            }
        });
    }

    private void capturarValor() {
        if (panelEditorActual != null) {
            panelEditorActual.capturarValor();
        }
    }

    public void actualizarArbolYRestaurarSeleccion() {
        actualizando = true;
        treeState.guardar();
        actualizarArbol();
        treeState.restaurar();
        actualizando = false;
    }
    
    private void actualizarArbol() {        

        TreePath path = arbolElementos.getSelectionPath();
        if (path == null) {
            return;
        }        
        while (path.getParentPath() != null) {
            path = path.getParentPath();
        }         
        modeloArbol.actualizar(path);        
    }

    private boolean guardarCambios() {
        capturarValor();
        boolean ok = estructura.guardarValores();
        if (ok) {
            Ventana.getInstancia().getMemorando().serializar("configurador.memo");
        }
        return ok;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        split = new javax.swing.JSplitPane();
        scrollArbol = new javax.swing.JScrollPane();
        arbolElementos = new javax.swing.JTree();
        panelVacio = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        botonAplicar = new javax.swing.JButton();
        filler2 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(32767, 0));
        botonAceptar = new javax.swing.JButton();
        filler1 = new javax.swing.Box.Filler(new java.awt.Dimension(8, 0), new java.awt.Dimension(8, 0), new java.awt.Dimension(8, 32767));
        botonCancelar = new javax.swing.JButton();

        setLayout(new java.awt.BorderLayout());

        split.setDividerLocation(300);

        scrollArbol.setMinimumSize(new java.awt.Dimension(230, 24));
        scrollArbol.setPreferredSize(new java.awt.Dimension(120, 324));
        scrollArbol.setViewportView(arbolElementos);

        split.setLeftComponent(scrollArbol);
        split.setRightComponent(panelVacio);

        add(split, java.awt.BorderLayout.CENTER);

        jPanel1.setBorder(javax.swing.BorderFactory.createEmptyBorder(6, 6, 6, 6));
        jPanel1.setLayout(new javax.swing.BoxLayout(jPanel1, javax.swing.BoxLayout.LINE_AXIS));

        botonAplicar.setText("Aplicar");
        botonAplicar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonAplicarActionPerformed(evt);
            }
        });
        jPanel1.add(botonAplicar);
        jPanel1.add(filler2);

        botonAceptar.setText("Aceptar");
        botonAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonAceptarActionPerformed(evt);
            }
        });
        jPanel1.add(botonAceptar);
        jPanel1.add(filler1);

        botonCancelar.setText("Cancelar");
        botonCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonCancelarActionPerformed(evt);
            }
        });
        jPanel1.add(botonCancelar);

        add(jPanel1, java.awt.BorderLayout.SOUTH);
    }// </editor-fold>//GEN-END:initComponents

    private void botonAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonAceptarActionPerformed
        if (!guardarCambios()) {
            return;
        }
        System.exit(0);
    }//GEN-LAST:event_botonAceptarActionPerformed

    private void botonCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonCancelarActionPerformed
        System.exit(0);
    }//GEN-LAST:event_botonCancelarActionPerformed

    private void botonAplicarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonAplicarActionPerformed
        guardarCambios();
    }//GEN-LAST:event_botonAplicarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTree arbolElementos;
    private javax.swing.JButton botonAceptar;
    private javax.swing.JButton botonAplicar;
    private javax.swing.JButton botonCancelar;
    private javax.swing.Box.Filler filler1;
    private javax.swing.Box.Filler filler2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel panelVacio;
    private javax.swing.JScrollPane scrollArbol;
    private javax.swing.JSplitPane split;
    // End of variables declaration//GEN-END:variables

}
